### ISSUE TITLE
A OPCODE doesn't Work

### ISSUE THREAD

**Issue by ColderCube** [docmarionum1/py65emu#4]
PHA  Push Accumulator on Stack
doesn't work

Here, Is the code

```python
import py65emu.mmu as m
import py65emu.cpu as c
import time
import cv2
import numpy as np
f=open('C:\\Users\\{mypc name}\\Downloads\\vasm6502\\vasm6502_oldstyle\\win\\win10\\a.out','rb')
color={ ' a dictionary containg colour for each value between 0 to 255 ' }
ram = np.zeros(shape=[16, 16, 3], dtype=np.uint8)
memory = m.MMU([(0x00,0x100),(0x1000,0x4000,True,[0xa9,0x02,0x48])])
cpu = c.CPU(memory,0x1000)
start = time.time()
while True:
    try:
        print(hex(cpu.r.pc),hex(cpu.r.s))
        cpu.step()
        print(cpu.r.a,cpu.r.x,cpu.r.y)

    except:
        break
#print(1/(time.time()-start))

x=0
y=0
for i in range(0,0x100):
    if x > 15:
        print()
        x=0
        y+=1
    print(memory.read(i),end=' ')

    ram[y][x]=color[memory.read(i)]
    x+=1
print(x,y)
ram=cv2.resize(ram,(300,300))
cv2.imshow('ram',ram)
cv2.waitKey(0)
```

OUTPUT 
```
0x1000 0xff
2 0 0
0x1002 0xff
0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 
0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 
0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 
0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 
0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 
0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 
0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 
0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 
0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 
0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 
0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 
0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 
0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 
0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 
0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 
0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 16 15

```

**Comment by docmarionum1** [comment]
@ArjunAbhijith The issue you're having with `PHA` is because your provided RAM doesn't include the default location of the stack.

The 6502 has the stack at 0x0100-0x1ff. You can either change the location of the stack

`cpu = c.CPU(memory,0x1000, stack_page=0)`

or you can provide more RAM

`memory = m.MMU([(0x00,0x200),(0x1000,0x4000,True,[0xa9,0x02,0x48])])`

**Comment by ArjunAbhijith** [comment]
jsr isn't working in my case idk why?

ERROR
`
Traceback (most recent call last):
  File "I:\windows 7\desktop\Python\Python 18-20 -3.7\6502\processor.py", line 26, in <module>
    cpu.step()
  File "C:\Users\Arjun\AppData\Local\Programs\Python\Python37\lib\site-packages\py65emu-0.0.0-py3.7.egg\py65emu\cpu.py", line 101, in step
    self.ops[opcode]()
  File "C:\Users\Arjun\AppData\Local\Programs\Python\Python37\lib\site-packages\py65emu-0.0.0-py3.7.egg\py65emu\cpu.py", line 591, in f
    op_f(a_f())
  File "C:\Users\Arjun\AppData\Local\Programs\Python\Python37\lib\site-packages\py65emu-0.0.0-py3.7.egg\py65emu\cpu.py", line 673, in BRK
    self.r.pc = self.interruptAddress('BRK')
  File "C:\Users\Arjun\AppData\Local\Programs\Python\Python37\lib\site-packages\py65emu-0.0.0-py3.7.egg\py65emu\cpu.py", line 155, in interruptAddress
    return self.mmu.readWord(self.interrupts[i])
  File "C:\Users\Arjun\AppData\Local\Programs\Python\Python37\lib\site-packages\py65emu-0.0.0-py3.7.egg\py65emu\mmu.py", line 123, in readWord
    return (self.read(addr+1) << 8) + self.read(addr)
  File "C:\Users\Arjun\AppData\Local\Programs\Python\Python37\lib\site-packages\py65emu-0.0.0-py3.7.egg\py65emu\mmu.py", line 118, in read
    b = self.getBlock(addr)
  File "C:\Users\Arjun\AppData\Local\Programs\Python\Python37\lib\site-packages\py65emu-0.0.0-py3.7.egg\py65emu\mmu.py", line 94, in getBlock
    raise IndexError
IndexError
`
ASSEMBLY CODE
`
  .org $1152

main:
	jsr hello

hello:
	rts

`

PYTHON CODE
`
import py65emu
from py65emu import mmu as M
from py65emu import cpu as C
import time
import numpy as np

MEMORY={"STACK":[0,0x200,False],
        "OUTPUT":[0x200,640,False],
        "CODE":[1153,63360,True,open('a.out','rb')]    
       }

m=M.MMU([MEMORY[i] for i in MEMORY])
cpu=C.CPU(m,1153,stack_page=0)
while True:
    print(m.read(cpu.r.pc))
    print(cpu.r.pc)
    cpu.step()
    print(cpu.r.getFlag)
`

**Comment by ArjunAbhijith** [comment]
It  is jumping to `0x1159` instead of `1159`

**Comment by docmarionum1** [comment]
I think it's because `.org $1152` is treating `$1152` as hex. `$` traditionally means treat the number as hex instead of decimal. So changing your address in python to `0x1152/3` should do the trick.
